### ISSUE TITLE
Open Form1

### ISSUE THREAD

**Issue by onlylau** [SzooX/TribalWarsBot#3]
Hi why when i try open Form1 design he miss some controls? thanks

**Comment by SzooX** [comment]
Hi , do you getting any errors suggesting which controls are missing?

**Comment by onlylau** [comment]
Hi bro, the Form1 have the same name "Name" as the table.... now its fix,
you are the owner?

SzooX ***@***.***> escreveu no dia terça, 27/09/2022 à(s)
08:26:

**Comment by onlylau** [comment]
Hi my friend, i just start improve your bot... its awesome what you did!
i'm just a new programmer, but i like to do bots. so i just need some help,
i wanna put the bot solving captcha using 2Captcha. Can you help me with
that? THANKS

marcos santos ***@***.***> escreveu no dia quarta,
28/09/2022 à(s) 23:39:

**Comment by SzooX** [comment]
Hi, sorry for late answer. I would love to help you with developing my bot and add futher features :). Could you add me somewhere else for fast contact? Since i have a lot of work in my job, i don't have that much time for developing this project, but of course that doesn't mean i leaved the project. Do you have discord? Mine is Crazy_#9623

**Comment by onlylau** [comment]
yap discord its fine, i ADD you Facethekings here


SzooX ***@***.***> escreveu no dia terça, 4/10/2022 à(s)
09:09:

**Comment by SzooX** [comment]
Added
